# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/libchimera
pkglibdir = $(libdir)/libchimera
pkgincludedir = $(includedir)/libchimera

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = i686-pc-linux-gnu
AR = ar
AS = @AS@
CC = gcc
CXX = g++
CXXCPP = g++ -E
DLLTOOL = @DLLTOOL@
ECHO = echo
EGREP = grep -E
EXEEXT = 
F77 = f95
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = libchimera
RANLIB = ranlib
RC = @RC@
STRIP = strip
VERSION = 1.4

bin_PROGRAMS = sha1_keygen test bighost bigtest monitor bignode sender receiver dhttest dht
LDADD = -L$(top_srcdir)/src -lchimera -lpthread -lcrypto
INCLUDES = -I$(top_srcdir)/include

sha1_keygen_SOURCES = sha1_keygen.c
test_SOURCES = test.c
sender_SOURCES = sender.c
receiver_SOURCE = receiver.c
bighost_SOURCE = bighost.c
bigtest_SOURCE = bigtest.c
monitor_SOURCE = monitor.c
bignode_SOURCE = bignode.c	
dht_SOURCE = dht.c
dhttest_SOURCE = dhttest.c
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
bin_PROGRAMS =  sha1_keygen$(EXEEXT) test$(EXEEXT) bighost$(EXEEXT) \
bigtest$(EXEEXT) monitor$(EXEEXT) bignode$(EXEEXT) sender$(EXEEXT) \
receiver$(EXEEXT) dhttest$(EXEEXT) dht$(EXEEXT)
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DPACKAGE_NAME=\"libchimera\" -DPACKAGE_TARNAME=\"libchimera\" -DPACKAGE_VERSION=\"1.4\" -DPACKAGE_STRING=\"libchimera\ 1.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"libchimera\" -DVERSION=\"1.4\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1  -I. -I$(srcdir) 
CPPFLAGS = 
LDFLAGS = 
LIBS = 
sha1_keygen_OBJECTS =  sha1_keygen.$(OBJEXT)
sha1_keygen_LDADD = $(LDADD)
sha1_keygen_DEPENDENCIES = 
sha1_keygen_LDFLAGS = 
test_OBJECTS =  test.$(OBJEXT)
test_LDADD = $(LDADD)
test_DEPENDENCIES = 
test_LDFLAGS = 
bighost_SOURCES = bighost.c
bighost_OBJECTS =  bighost.$(OBJEXT)
bighost_LDADD = $(LDADD)
bighost_DEPENDENCIES = 
bighost_LDFLAGS = 
bigtest_SOURCES = bigtest.c
bigtest_OBJECTS =  bigtest.$(OBJEXT)
bigtest_LDADD = $(LDADD)
bigtest_DEPENDENCIES = 
bigtest_LDFLAGS = 
monitor_SOURCES = monitor.c
monitor_OBJECTS =  monitor.$(OBJEXT)
monitor_LDADD = $(LDADD)
monitor_DEPENDENCIES = 
monitor_LDFLAGS = 
bignode_SOURCES = bignode.c
bignode_OBJECTS =  bignode.$(OBJEXT)
bignode_LDADD = $(LDADD)
bignode_DEPENDENCIES = 
bignode_LDFLAGS = 
sender_OBJECTS =  sender.$(OBJEXT)
sender_LDADD = $(LDADD)
sender_DEPENDENCIES = 
sender_LDFLAGS = 
receiver_SOURCES = receiver.c
receiver_OBJECTS =  receiver.$(OBJEXT)
receiver_LDADD = $(LDADD)
receiver_DEPENDENCIES = 
receiver_LDFLAGS = 
dhttest_SOURCES = dhttest.c
dhttest_OBJECTS =  dhttest.$(OBJEXT)
dhttest_LDADD = $(LDADD)
dhttest_DEPENDENCIES = 
dhttest_LDFLAGS = 
dht_SOURCES = dht.c
dht_OBJECTS =  dht.$(OBJEXT)
dht_LDADD = $(LDADD)
dht_DEPENDENCIES = 
dht_LDFLAGS = 
CFLAGS = -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
DEP_FILES =  .deps/bighost.P .deps/bignode.P .deps/bigtest.P .deps/dht.P \
.deps/dhttest.P .deps/monitor.P .deps/receiver.P .deps/sender.P \
.deps/sha1_keygen.P .deps/test.P
SOURCES = $(sha1_keygen_SOURCES) $(test_SOURCES) bighost.c bigtest.c monitor.c bignode.c $(sender_SOURCES) receiver.c dhttest.c dht.c
OBJECTS = $(sha1_keygen_OBJECTS) $(test_OBJECTS) bighost.$(OBJEXT) bigtest.$(OBJEXT) monitor.$(OBJEXT) bignode.$(OBJEXT) $(sender_OBJECTS) receiver.$(OBJEXT) dhttest.$(OBJEXT) dht.$(OBJEXT)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu test/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

sha1_keygen$(EXEEXT): $(sha1_keygen_OBJECTS) $(sha1_keygen_DEPENDENCIES)
	@rm -f sha1_keygen$(EXEEXT)
	$(LINK) $(sha1_keygen_LDFLAGS) $(sha1_keygen_OBJECTS) $(sha1_keygen_LDADD) $(LIBS)

test$(EXEEXT): $(test_OBJECTS) $(test_DEPENDENCIES)
	@rm -f test$(EXEEXT)
	$(LINK) $(test_LDFLAGS) $(test_OBJECTS) $(test_LDADD) $(LIBS)

bighost$(EXEEXT): $(bighost_OBJECTS) $(bighost_DEPENDENCIES)
	@rm -f bighost$(EXEEXT)
	$(LINK) $(bighost_LDFLAGS) $(bighost_OBJECTS) $(bighost_LDADD) $(LIBS)

bigtest$(EXEEXT): $(bigtest_OBJECTS) $(bigtest_DEPENDENCIES)
	@rm -f bigtest$(EXEEXT)
	$(LINK) $(bigtest_LDFLAGS) $(bigtest_OBJECTS) $(bigtest_LDADD) $(LIBS)

monitor$(EXEEXT): $(monitor_OBJECTS) $(monitor_DEPENDENCIES)
	@rm -f monitor$(EXEEXT)
	$(LINK) $(monitor_LDFLAGS) $(monitor_OBJECTS) $(monitor_LDADD) $(LIBS)

bignode$(EXEEXT): $(bignode_OBJECTS) $(bignode_DEPENDENCIES)
	@rm -f bignode$(EXEEXT)
	$(LINK) $(bignode_LDFLAGS) $(bignode_OBJECTS) $(bignode_LDADD) $(LIBS)

sender$(EXEEXT): $(sender_OBJECTS) $(sender_DEPENDENCIES)
	@rm -f sender$(EXEEXT)
	$(LINK) $(sender_LDFLAGS) $(sender_OBJECTS) $(sender_LDADD) $(LIBS)

receiver$(EXEEXT): $(receiver_OBJECTS) $(receiver_DEPENDENCIES)
	@rm -f receiver$(EXEEXT)
	$(LINK) $(receiver_LDFLAGS) $(receiver_OBJECTS) $(receiver_LDADD) $(LIBS)

dhttest$(EXEEXT): $(dhttest_OBJECTS) $(dhttest_DEPENDENCIES)
	@rm -f dhttest$(EXEEXT)
	$(LINK) $(dhttest_LDFLAGS) $(dhttest_OBJECTS) $(dhttest_LDADD) $(LIBS)

dht$(EXEEXT): $(dht_OBJECTS) $(dht_DEPENDENCIES)
	@rm -f dht$(EXEEXT)
	$(LINK) $(dht_LDFLAGS) $(dht_OBJECTS) $(dht_LDADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = test

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu test/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
		clean-depend clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
		distclean-tags distclean-depend distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir \
mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
