"function AuthProfile()\n"
"{\n"
"  this._accessList = new AccessList();\n"
"  this._realm = \"karoo\";\n"
"}\n"
"\n"
"AuthProfile.prototype = new TransactionProfile();\n"
"\n"
"AuthProfile.prototype.verify = function(request)\n"
"{\n"
"  var sipMessage = new SIPMessage(request);\n"
"  if (this._accessList.verify(request))\n"
"  {\n"
"    return this.setProperties(sipMessage);\n"
"  }\n"
"  return false;\n"
"}\n"
"\n"
