"\n"
"\n"
"function AccessList()\n"
"{\n"
"  this._trustedNetwork = [];\n"
"  this._trustEveryone = false;\n"
"}\n"
"\n"
"AccessList.prototype.verify = function(request)\n"
"{\n"
"  var sipMessage = new SIPMessage(request);\n"
"\n"
"  if (this._trustEveryone)\n"
"  {\n"
"    sipMessage.setProperty(\"auth-action\", \"accept\");\n"
"    return true;\n"
"  }\n"
"\n"
"  var  sourceAddress = sipMessage.getSourceAddress();\n"
"  var i;\n"
"  for(i=0; i < this._trustedNetwork.length; i++)\n"
"  {\n"
"    var network = this._trustedNetwork[i];\n"
"    log_info(sipMessage.getLogId(), \"Verifying \" + sourceAddress + \" against \" + network )\n"
"    if (cidrVerify(sourceAddress, network))\n"
"    {\n"
"      sipMessage.setProperty(\"auth-action\", \"accept\");\n"
"      return true;\n"
"    }\n"
"  }\n"
"  sipMessage.setProperty(\"auth-action\", \"reject\");\n"
"  return false;\n"
"}\n"
