"\n"
"\n"
"function PropertyObject(pname, value, requestType)\n"
"{\n"
"  this._name = pname;\n"
"  this._value = value;\n"
"  this._requestType = requestType;\n"
"}\n"
"\n"
"PropertyObject.prototype.set = function(pname, value, requestType)\n"
"{\n"
"  this._name = pname;\n"
"  this._value = value;\n"
"  this._requestType = requestType;\n"
"}\n"
"\n"
"\n"
