"function TransactionProfile()\n"
"{\n"
"  this._transactionParams = [];\n"
"}\n"
"\n"
"TransactionProfile.prototype.setProperties = function(sipMessage)\n"
"{\n"
"    var i = 0;\n"
"    for (i = 0; i < this._transactionParams.length; i++)\n"
"    {\n"
"      var property = this._transactionParams[i];\n"
"      if (property._requestType == \"*\")\n"
"      {\n"
"        sipMessage.setTransactionProperty(property._name, property._value);\n"
"      }\n"
"      else if (sipMessage.isRequest(property._requestType))\n"
"      {\n"
"        sipMessage.setTransactionProperty(property._name, property._value);\n"
"      }\n"
"    }\n"
"    return true;\n"
"}\n"
